name: Deploy to Vercel

on:
  push:
    branches:
      - TP-2  # Remplacez par votre branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Utilisez une version compatible avec Angular

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: ng build --prod

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ jAeJiv6Ir8jixjyhOHbH77DX }}
